name: CI Pipeline

on:
  push:
    branches:
      - main
      - "**" # Run on all branches
  pull_request:
    branches:
      - "**"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r backend/tests/requirements.txt

  linting:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Run linting
        run: |
          python -m venv venv
          . venv/bin/activate
          backend/tests/linting/intest yamllint pylint unixmode

  unit-test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r backend/tests/requirements.txt

      - name: Debug environment
        run: echo "CI=$CI"

      - name: Run unit tests with coverage
        env:
        run: |
          . venv/bin/activate
          ./backend/tests/coveragetest
