name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: lee
          POSTGRES_PASSWORD: supersecretpassword
          POSTGRES_DB: crowdhype_db
        ports:
          - 5432:5432
        options: >
          --health-cmd="pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Configure .pgpass for PostgreSQL
        run: |
          echo "localhost:5432:crowdhype_db:lee:supersecretpassword" > ~/.pgpass
          chmod 600 ~/.pgpass

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U lee -d crowdhype_db; do
            echo "Waiting for PostgreSQL to be ready...";
            sleep 1;
          done

      - name: Test Database Connection
        env:
          PGPASSWORD: supersecretpassword
        run: |
          psql -U lee -d crowdhype_db -h localhost -c '\l'
      - name: Install Dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Migrations
        run: |
          . venv/bin/activate
          python backend/manage.py migrate
        env:
          CI: true

  linting:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Run linting
        run: |
          python -m venv venv
          . venv/bin/activate
          backend/tests/linting/intest yamllint pylint unixmode

  unit-test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r backend/tests/requirements.txt

      - name: Debug environment
        run: echo "CI=$CI"

      - name: Run unit tests with coverage
        run: |
          . venv/bin/activate
          ./backend/tests/coveragetest
